#!/usr/bin/env python
# Copyright (c) 2019 - The Procedural Generation for Gazebo authors
# For information on the respective copyright owner see the NOTICE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific
from pcg_gazebo.simulation import SimulationModel, is_gazebo_model
import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser('Open and display a Gazebo model')
    parser.add_argument(
        '--model',
        '-m', type=str, help='Gazebo model name')
    parser.add_argument(
        '--collision',
        '-c', action='store_true',
        help='View collision meshes')

    args = parser.parse_args()

    assert is_gazebo_model(args.model), \
        '{} is an invalid model or is not the resources path'.format(
            args.model)

    model = SimulationModel.from_gazebo_model(args.model)

    if args.collision:
        model.show(mesh_type='collision')
    else:
        model.show(mesh_type='visual')
