#!/usr/bin/env python
# Copyright (c) 2019 - The Procedural Generation for Gazebo authors
# For information on the respective copyright owner see the NOTICE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific
import argparse
import trimesh
import os


if __name__ == '__main__':
    parser = argparse.ArgumentParser('Open and display a mesh')
    parser.add_argument('--filename', '-f', type=str, help='Mesh filename')

    args = parser.parse_args()

    assert os.path.isfile(args.filename), 'Invalid mesh filename'

    mesh = trimesh.load_mesh(args.filename)
    mesh.show()
